### ISSUE TITLE
[Analyze] - get profile of user

### ISSUE THREAD

**Issue by tvc12** [4pet-social/ext-post-service#13]
+ Need get account info
  + Input: accountId
  + output: User

+ Search post
  + Input: accountID, offset, limit
  + Ouput:
```
{
data: List<Post>,
total: Int
}
```

**👀 View [example template](https://github.com/4pet-social/docs/blob/master/docs/analyze/.NetCore.md)**

**Comment by tvc12** [comment]
+ Need get account info
+ Search my post

**Comment by tvc12** [comment]
Hỏi thêm thì ib @tvc12

**Comment by tvc12** [comment]
Dealine: 23:55 19/05/2020

**Comment by meantg** [comment]
[https://app.zenhub.com/files/250709386/92ee3404-0b37-4128-8779-c8548ac92e6e/download](https://app.zenhub.com/files/250709386/92ee3404-0b37-4128-8779-c8548ac92e6e/download)

**Comment by meantg** [comment]
Link word drive 
https://drive.google.com/file/d/167MO8xVNLak6qnFkxLdwrFhKx1PmboAG/view?usp=sharing

**Comment by tvc12** [comment]
Stop
